name: Notify on Code Change

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Repo Updated"
          to: yourmail@gmail.com
          from: yourmail@gmail.com
          body: |
            Code updated in repository!
            
            Commit Message: ${{ github.event.head_commit.message }}
            Author: ${{ github.actor }}